// Auth action types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGOUT = 'LOGOUT';
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

// Itinerary action types
export const FETCH_ITINERARIES_REQUEST = 'FETCH_ITINERARIES_REQUEST';
export const FETCH_ITINERARIES_SUCCESS = 'FETCH_ITINERARIES_SUCCESS';
export const FETCH_ITINERARIES_FAILURE = 'FETCH_ITINERARIES_FAILURE';
export const FETCH_ITINERARY_REQUEST = 'FETCH_ITINERARY_REQUEST';
export const FETCH_ITINERARY_SUCCESS = 'FETCH_ITINERARY_SUCCESS';
export const FETCH_ITINERARY_FAILURE = 'FETCH_ITINERARY_FAILURE';
export const CREATE_ITINERARY_REQUEST = 'CREATE_ITINERARY_REQUEST';
export const CREATE_ITINERARY_SUCCESS = 'CREATE_ITINERARY_SUCCESS';
export const CREATE_ITINERARY_FAILURE = 'CREATE_ITINERARY_FAILURE';
export const UPDATE_ITINERARY_REQUEST = 'UPDATE_ITINERARY_REQUEST';
export const UPDATE_ITINERARY_SUCCESS = 'UPDATE_ITINERARY_SUCCESS';
export const UPDATE_ITINERARY_FAILURE = 'UPDATE_ITINERARY_FAILURE';
export const DELETE_ITINERARY_REQUEST = 'DELETE_ITINERARY_REQUEST';
export const DELETE_ITINERARY_SUCCESS = 'DELETE_ITINERARY_SUCCESS';
export const DELETE_ITINERARY_FAILURE = 'DELETE_ITINERARY_FAILURE';
export const GENERATE_ITINERARY_REQUEST = 'GENERATE_ITINERARY_REQUEST';
export const GENERATE_ITINERARY_SUCCESS = 'GENERATE_ITINERARY_SUCCESS';
export const GENERATE_ITINERARY_FAILURE = 'GENERATE_ITINERARY_FAILURE';
export const FAVORITE_ITINERARY_REQUEST = 'FAVORITE_ITINERARY_REQUEST';
export const FAVORITE_ITINERARY_SUCCESS = 'FAVORITE_ITINERARY_SUCCESS';
export const FAVORITE_ITINERARY_FAILURE = 'FAVORITE_ITINERARY_FAILURE';

// Preference action types
export const FETCH_PREFERENCES_REQUEST = 'FETCH_PREFERENCES_REQUEST';
export const FETCH_PREFERENCES_SUCCESS = 'FETCH_PREFERENCES_SUCCESS';
export const FETCH_PREFERENCES_FAILURE = 'FETCH_PREFERENCES_FAILURE';
export const UPDATE_PREFERENCES_REQUEST = 'UPDATE_PREFERENCES_REQUEST';
export const UPDATE_PREFERENCES_SUCCESS = 'UPDATE_PREFERENCES_SUCCESS';
export const UPDATE_PREFERENCES_FAILURE = 'UPDATE_PREFERENCES_FAILURE';